config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :salespeople

  resources :customers

  resources :statuses

  resources :amorts

  resources :vehicles

  resources :colors

  resources :types

  resources :models

  resources :makes

  root 'vehicles#index'

end

app/models/amort.rb
class Amort < ActiveRecord::Base

end

app/models/color.rb
class Color < ActiveRecord::Base
  belongs_to :vehicle
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_one :status
  belongs_to :quote

  def self.search(search)
    if search
      where(['last_name LIKE ? OR first_name LIKE ?', "%#{search}%","%#{search}%"])
    else
      all
    end
  end

  def fullname
    name = first_name + ' ' + last_name
  end
end

app/models/make.rb
class Make < ActiveRecord::Base
  has_many :models
  belongs_to :vehicle
end

app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to :vehicle
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  has_many :customers
  has_many :vehicles
  has_many :salespeople

end

app/models/salesperson.rb
class Salesperson < ActiveRecord::Base
  belongs_to :quote

  def fullname
    name = first_name + ' ' + last_name
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :customer
end

app/models/type.rb
class Type < ActiveRecord::Base
  belongs_to :vehicle
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_many :colors
  has_many :types
  has_many :makes
  has_many :models

  def self.search(search)
    if search
      where(['vin LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name)
    end
end

app/helpers/amorts_helper.rb
module AmortsHelper
  def htmlrender(principal,int_rate,months)
    p = principal
    r = ((int_rate/100.to_f)/12).to_f
    n = months
    bal = principal
    pmt_amt = p * ((r*((1+r)**n))/(((1+r)**n)-1))
    pmt_int = r * bal
    pmt_p = pmt_amt - pmt_int
    amort_schedule = [number_to_currency(bal)]

    i = 0
    while i < n do
      pmt_int = r * bal
      bal = bal + pmt_int - pmt_amt
      pmt_p = pmt_amt - pmt_int
      amort_schedule.push(number_to_currency(pmt_amt),number_to_currency(pmt_int),number_to_currency(pmt_p),number_to_currency(bal))

      i += 1
    end

    i = 1
    j = 1
    htmlstring = "<table><thead><tr><th>Payment</th><th>Payment<br>Amount</th><th>Interest</th><th>Principal</th><th>Balance</th></tr></thead><tbody><tr><td><b>0</b></td><td></td><td></td><td></td><td>" + amort_schedule[0].to_s + "</td></tr>"
    bodystring = ""
    while i < amort_schedule.length do
      bodystring = bodystring + "<tr><td><b>" + j.to_s + "</b></td><td>" + amort_schedule[i].to_s + "</td><td>" + amort_schedule[i+1].to_s + "</td><td>" + amort_schedule[i+2].to_s + "</td><td>" + amort_schedule[i+3].to_s + "</td></tr>"
      i += 4
      j += 1
    end
    htmlstring = htmlstring + bodystring + "</tbody></table>"

    return htmlstring
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
  def htmlrender(principal,int_rate,months)
    p = principal
    r = ((int_rate/100.to_f)/12).to_f
    n = months
    bal = principal
    pmt_amt = p * ((r*((1+r)**n))/(((1+r)**n)-1))
    pmt_int = r * bal
    pmt_p = pmt_amt - pmt_int
    amort_schedule = [number_to_currency(bal)]

    i = 0
    while i < n do
      pmt_int = r * bal
      bal = bal + pmt_int - pmt_amt
      pmt_p = pmt_amt - pmt_int
      amort_schedule.push(number_to_currency(pmt_amt),number_to_currency(pmt_int),number_to_currency(pmt_p),number_to_currency(bal))

      i += 1
    end

    i = 1
    j = 1
    htmlstring = "<table><thead><tr><th>Payment</th><th>Payment<br>Amount</th><th>Interest</th><th>Principal</th><th>Balance</th></tr></thead><tbody><tr><td><b>0</b></td><td></td><td></td><td></td><td>" + amort_schedule[0].to_s + "</td></tr>"
    bodystring = ""
    while i < amort_schedule.length do
      bodystring = bodystring + "<tr><td><b>" + j.to_s + "</b></td><td>" + amort_schedule[i].to_s + "</td><td>" + amort_schedule[i+1].to_s + "</td><td>" + amort_schedule[i+2].to_s + "</td><td>" + amort_schedule[i+3].to_s + "</td></tr>"
      i += 4
      j += 1
    end
    htmlstring = htmlstring + bodystring + "</tbody></table>"

    return htmlstring
  end
end

app/helpers/salespeople_helper.rb
module SalespeopleHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<p></p>
<table>
  <td><%= link_to 'Colors', colors_path %></td>
  <td><%= link_to 'Makes', makes_path %></td>
  <td><%= link_to 'Models', models_path %></td>
</table>
<h1>Editing Type</h1>

<%= render 'form' %>

<%= link_to 'New Type', new_type_path %> |
<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>
<table>
  <td><%= link_to 'Colors', colors_path %></td>
  <td><%= link_to 'Makes', makes_path %></td>
  <td><%= link_to 'Models', models_path %></td>
</table>
<h2>Vehicle Types</h2>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.name %></td>
        <td><%= link_to 'Show', type %> <%= link_to 'Edit', edit_type_path(type) %> <%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<p></p>
<table>
  <td><%= link_to 'Colors', colors_path %></td>
  <td><%= link_to 'Makes', makes_path %></td>
  <td><%= link_to 'Models', models_path %></td>
</table>
<h1>New Type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>
<table>
  <td><%= link_to 'Colors', colors_path %></td>
  <td><%= link_to 'Makes', makes_path %></td>
  <td><%= link_to 'Models', models_path %></td>
</table>
<p>
  <strong>Type:</strong>
  <%= @type.name %>
</p>

<%= link_to 'New Type', new_type_path %> |
<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>