config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :salespeople

  resources :customers

  resources :statuses

  resources :amorts

  resources :vehicles

  resources :colors

  resources :types

  resources :models

  resources :makes

  root 'vehicles#index'

end

app/models/amort.rb
class Amort < ActiveRecord::Base

end

app/models/color.rb
class Color < ActiveRecord::Base
  belongs_to :vehicle
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_one :status
  belongs_to :quote

  def self.search(search)
    if search
      where(['last_name LIKE ? OR first_name LIKE ?', "%#{search}%","%#{search}%"])
    else
      all
    end
  end

  def fullname
    name = first_name + ' ' + last_name
  end
end

app/models/make.rb
class Make < ActiveRecord::Base
  has_many :models
  belongs_to :vehicle
end

app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to :vehicle
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  has_many :customers
  has_many :vehicles
  has_many :salespeople

end

app/models/salesperson.rb
class Salesperson < ActiveRecord::Base
  belongs_to :quote

  def fullname
    name = first_name + ' ' + last_name
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :customer
end

app/models/type.rb
class Type < ActiveRecord::Base
  belongs_to :vehicle
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_many :colors
  has_many :types
  has_many :makes
  has_many :models

  def self.search(search)
    if search
      where(['vin LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/controllers/makes_controller.rb
class MakesController < ApplicationController
  before_action :set_make, only: [:show, :edit, :update, :destroy]

  # GET /makes
  # GET /makes.json
  def index
    @makes = Make.all
  end

  # GET /makes/1
  # GET /makes/1.json
  def show
  end

  # GET /makes/new
  def new
    @make = Make.new
  end

  # GET /makes/1/edit
  def edit
  end

  # POST /makes
  # POST /makes.json
  def create
    @make = Make.new(make_params)

    respond_to do |format|
      if @make.save
        format.html { redirect_to @make, notice: 'Make was successfully created.' }
        format.json { render :show, status: :created, location: @make }
      else
        format.html { render :new }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /makes/1
  # PATCH/PUT /makes/1.json
  def update
    respond_to do |format|
      if @make.update(make_params)
        format.html { redirect_to @make, notice: 'Make was successfully updated.' }
        format.json { render :show, status: :ok, location: @make }
      else
        format.html { render :edit }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /makes/1
  # DELETE /makes/1.json
  def destroy
    @make.destroy
    respond_to do |format|
      format.html { redirect_to makes_url, notice: 'Make was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_make
      @make = Make.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def make_params
      params.require(:make).permit(:name)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.search(params[:search])
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:vin, :year, :color_id, :make_id, :model_id, :type_id, :msrp, :cost)
    end
end

app/helpers/amorts_helper.rb
module AmortsHelper
  def htmlrender(principal,int_rate,months)
    p = principal
    r = ((int_rate/100.to_f)/12).to_f
    n = months
    bal = principal
    pmt_amt = p * ((r*((1+r)**n))/(((1+r)**n)-1))
    pmt_int = r * bal
    pmt_p = pmt_amt - pmt_int
    amort_schedule = [number_to_currency(bal)]

    i = 0
    while i < n do
      pmt_int = r * bal
      bal = bal + pmt_int - pmt_amt
      pmt_p = pmt_amt - pmt_int
      amort_schedule.push(number_to_currency(pmt_amt),number_to_currency(pmt_int),number_to_currency(pmt_p),number_to_currency(bal))

      i += 1
    end

    i = 1
    j = 1
    htmlstring = "<table><thead><tr><th>Payment</th><th>Payment<br>Amount</th><th>Interest</th><th>Principal</th><th>Balance</th></tr></thead><tbody><tr><td><b>0</b></td><td></td><td></td><td></td><td>" + amort_schedule[0].to_s + "</td></tr>"
    bodystring = ""
    while i < amort_schedule.length do
      bodystring = bodystring + "<tr><td><b>" + j.to_s + "</b></td><td>" + amort_schedule[i].to_s + "</td><td>" + amort_schedule[i+1].to_s + "</td><td>" + amort_schedule[i+2].to_s + "</td><td>" + amort_schedule[i+3].to_s + "</td></tr>"
      i += 4
      j += 1
    end
    htmlstring = htmlstring + bodystring + "</tbody></table>"

    return htmlstring
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
  def htmlrender(principal,int_rate,months)
    p = principal
    r = ((int_rate/100.to_f)/12).to_f
    n = months
    bal = principal
    pmt_amt = p * ((r*((1+r)**n))/(((1+r)**n)-1))
    pmt_int = r * bal
    pmt_p = pmt_amt - pmt_int
    amort_schedule = [number_to_currency(bal)]

    i = 0
    while i < n do
      pmt_int = r * bal
      bal = bal + pmt_int - pmt_amt
      pmt_p = pmt_amt - pmt_int
      amort_schedule.push(number_to_currency(pmt_amt),number_to_currency(pmt_int),number_to_currency(pmt_p),number_to_currency(bal))

      i += 1
    end

    i = 1
    j = 1
    htmlstring = "<table><thead><tr><th>Payment</th><th>Payment<br>Amount</th><th>Interest</th><th>Principal</th><th>Balance</th></tr></thead><tbody><tr><td><b>0</b></td><td></td><td></td><td></td><td>" + amort_schedule[0].to_s + "</td></tr>"
    bodystring = ""
    while i < amort_schedule.length do
      bodystring = bodystring + "<tr><td><b>" + j.to_s + "</b></td><td>" + amort_schedule[i].to_s + "</td><td>" + amort_schedule[i+1].to_s + "</td><td>" + amort_schedule[i+2].to_s + "</td><td>" + amort_schedule[i+3].to_s + "</td></tr>"
      i += 4
      j += 1
    end
    htmlstring = htmlstring + bodystring + "</tbody></table>"

    return htmlstring
  end
end

app/helpers/salespeople_helper.rb
module SalespeopleHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vin %><br>
    <%= f.text_field :vin %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :color_id %><br>
    <%= f.collection_select :color_id,Color.all,:id,:name,:prompt => 'Select a Color' %>
  </div>
  <div class="field">
    <%= f.label :make_id %><br>
    <%= f.collection_select :make_id,Make.all,:id,:name,:prompt => 'Select a Make' %>
  </div>
  <div class="field">
    <%= f.label :model_id %><br>
    <%= f.collection_select :model_id,Model.all,:id,:name,:prompt => 'Select a Model' %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br>
    <%= f.collection_select :type_id,Type.all,:id,:name,:prompt => 'Select a Type' %>
  </div>
  <div class="field">
    <%= f.label :msrp %><br>
    <%= f.text_field :msrp %>
  </div>
  <div class="field">
    <%= f.label :dealer_cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>
<table>
  <td><%= link_to 'Colors', colors_path %></td>
  <td><%= link_to 'Makes', makes_path %></td>
  <td><%= link_to 'Models', models_path %></td>
  <td><%= link_to 'Types', types_path %></td>
</table>
<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>VIN</th>
      <th>Year</th>
      <th>Color</th>
      <th>Make</th>
      <th>Model</th>
      <th>Type</th>
      <th>MSRP</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.vin %></td>
        <td><%= vehicle.year %></td>
        <td><%= Color.find(vehicle.color_id).name %></td>
        <td><%= Make.find(vehicle.make_id).name %></td>
        <td><%= Model.find(vehicle.model_id).name %></td>
        <td><%= Type.find(vehicle.type_id).name %></td>
        <td><%= number_to_currency(vehicle.msrp) %></td>
        <td><%= number_to_currency(vehicle.cost) %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>
<%= form_tag vehicles_path, :method => 'get' do %>
    <p>
      Vehicle Search<br>
      (by Color, Model or VIN)
      <br>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>VIN:</strong>
  <%= @vehicle.vin %>
<br>
  <strong>Year:</strong>
  <%= @vehicle.year %>
  <br>
  <strong>Color:</strong>
  <%= Color.find(@vehicle.color_id).name %>
  <br>
  <strong>Make:</strong>
  <%= Make.find(@vehicle.make_id).name %>
  <br>
  <strong>Model:</strong>
  <%= Model.find(@vehicle.model_id).name %>
  <br>
  <strong>Type:</strong>
  <%= Type.find(@vehicle.type_id).name %>
  <br>
  <strong>Msrp:</strong>
  <%= number_to_currency(@vehicle.msrp) %>
<br>
  <strong>Cost:</strong>
  <%= number_to_currency(@vehicle.cost) %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>